# <center> 实验2：Numpy实验</center>

In [74]:
import numpy as np

### 题目1：数组分块求和
随机创建一个形状为 (4, 4) 的整数数组（元素范围0-100）。将其划分为 2x2 的子数组，并计算每个子数组的和。



In [75]:
# 设置随机种子以便结果可重现
np.random.seed(42)
array = np.random.randint(0, 101, size=(4, 4))
print(array)
array_splitted = map(np.array_split,np.array_split(array, 2),[2,2],[1,1])
array_splitted = array_splitted.__next__()+array_splitted.__next__()
print(np.array(list(map(np.sum,array_splitted))).reshape(2,2))


[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]
[[223 253]
 [173 259]]


### 题目2：数组滑动窗口
随机生成一个长度为10的一维整数数组（元素范围0-100）。计算大小为 3 的滑动窗口的平均值（取整）。


In [76]:
# 设置随机种子以便结果可重现
np.random.seed(42)
array = np.random.randint(0, 101, size=(1,10))
print(f"原始数组: {array}")
array_mean = np.array([int(np.mean(array[:,i:i+3])) for i in range(array.shape[1]-2)])
print(f"滑动窗口平均值（整数）: {array_mean}")



原始数组: [[51 92 14 71 60 20 82 86 74 74]]
滑动窗口平均值（整数）: [52 59 48 50 54 62 80 78]


### 题目3：数组对角线填充
给定一个形状为 (5, 5) 的数组，将其主对角线元素填充为 1，对角线两侧的元素填充为 2，其余元素为 0。

In [77]:

array = np.eye(5).flatten()
for i in range(array.shape[0]):
    if array[i] == 1:
        if i > 0:
            array[i-1] = 2
        if i < array.shape[0] - 1:
            array[i+1] = 2
print(array.reshape(5, 5))

[[1. 2. 0. 0. 0.]
 [2. 1. 2. 0. 0.]
 [0. 2. 1. 2. 0.]
 [0. 0. 2. 1. 2.]
 [0. 0. 0. 2. 1.]]


### 题目4：数组条件替换
随机生成一个长度为10的整数数组（元素范围0-9），将所有大于 5 的元素替换为 1，其余替换为 0。

In [78]:
# 设置随机种子以便结果可重现
np.random.seed(42)
array = np.random.randint(0, 10, size=(1, 10))
print(f"原始数组: {array}")
array_if = (array>5).astype(int)
print(f"替换后数组: {array_if}")

原始数组: [[6 3 7 4 6 9 2 6 7 4]]
替换后数组: [[1 0 1 0 1 1 0 1 1 0]]


### 题目5：数组分组统计
随机生成一个长度为9的整数数组（元素范围0-9），随机生成一个长度为9的分组索引，索引取值为0，1，2。求每组的平均值


In [79]:
# 设置随机种子以便结果可重现
np.random.seed(22)
array = np.random.randint(0, 10, size=(1,9))
print(f"原始数组: {array}")
array_group = np.random.randint(0, 3, size=(1,9))
print(f"分组索引: {array_group}")
print(np.array([np.mean(array[array_group==i]) for i in range(3)]))

原始数组: [[5 4 0 4 6 6 4 8 4]]
分组索引: [[1 2 2 0 1 0 2 1 2]]
[5.         6.33333333 3.        ]


### 题目6：数组元素筛选
随机生成一个长度为20的整数数组（元素范围0-100），筛选出所有偶数元素。


In [80]:
# 设置随机种子以便结果可重现
np.random.seed(42)
array = np.random.randint(0, 101, size=(1,20))
print(f"原始数组: {array}")
array_if = np.array(list(filter(lambda x: x%2 == 0 , array.flatten())))
print(f"偶数数组: {array_if}")


原始数组: [[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]]
偶数数组: [92 14 60 20 82 86 74 74  2 52]


### 题目7：数组统计计算
创建一个4×5的随机整数数组（元素范围10-50），计算：
- 所有元素的平均值、中位数
- 每列的最大值、每行的最小值
- 数组的标准差、方差
- 数组元素总和

In [81]:
# 设置随机种子以便结果可重现
np.random.seed(42)
array = np.random.randint(10,51,size=(4,5))
print(f"随机数组: {array}")
print("平均值: %.2f" % np.mean(array))
print("中位数: %.2f" % np.median(array))
print(f"每列最大值: {np.max(array, axis=0)}")
print(f"每列最小值: {np.min(array, axis=0)}")
print("标准差: %.2f" % np.std(array))
print("方差: %.2f" % np.var(array))
print(f"元素总和: {np.sum(array)}")


随机数组: [[48 38 24 17 30]
 [48 28 32 20 20]
 [33 45 49 33 12]
 [31 11 33 39 47]]
平均值: 31.90
中位数: 32.50
每列最大值: [48 45 49 39 47]
每列最小值: [31 11 24 17 12]
标准差: 11.67
方差: 136.09
元素总和: 638


### 题目8：数组归一化
随机生成一个长度为10的整数数组（元素范围0-9），将其归一化到 [0, 1] 范围，小数点后保留2位。


In [82]:
# 设置随机种子保证结果可重现
np.random.seed(42)
array = np.random.randint(0,10,size=(1,10))
print(f"原始随机数组: {array}")
array_min = np.min(array)
array_max = np.max(array)
array = np.array(list(map(lambda x: (x-array_min)/(array_max-array_min), array.flatten()))).round(decimals=2)
print(f"归一化后的数组: {array}")


原始随机数组: [[6 3 7 4 6 9 2 6 7 4]]
归一化后的数组: [0.57 0.14 0.71 0.29 0.57 1.   0.   0.57 0.71 0.29]


### 题目9：数组逻辑运算
给定两个布尔数组 a = [True, False, True] 和 b = [False, False, True]，计算它们的逻辑与、逻辑或和数组a的逻辑非。


In [83]:
a = np.array([True, False, True])
b = np.array([False, False, True])
print(f"逻辑与: {np.logical_and(a, b)}")
print(f"逻辑或: {np.logical_or(a, b)}")
print(f"逻辑非: {np.logical_not(a)}")

逻辑与: [False False  True]
逻辑或: [ True False  True]
逻辑非: [False  True False]


### 题目10：数组拼接与拆分
给定两个数组 a = [1, 2, 3, 4] 和 b = [5, 6, 7, 8]，将它们按行拼接成一个新数组，然后将新数组再水平拆分（按列拆分）为两个子数组。


In [84]:

a = np.array([[1, 2, 3 ,4]])
b = np.array([[5, 6, 7, 8]])
a_b = np.concatenate((a,b), axis=0)
print(f"拼接后数组: \n{a_b}")
print(f"拆分后数组1：\n{a_b[:,:2]}")
print(f"拆分后数组2：\n{a_b[:,2:]}")

拼接后数组: 
[[1 2 3 4]
 [5 6 7 8]]
拆分后数组1：
[[1 2]
 [5 6]]
拆分后数组2：
[[3 4]
 [7 8]]


### 题目11：数组标准化
随机生成一个长度为10的整数数组（元素范围10-50），将其z-score标准化，计算标准化后的数据的均值和标准差，小数点后保留2位。。


In [85]:

# 设置随机种子保证结果可重现
np.random.seed(42)
array = np.random.randint(10, 51, size=(1, 10))
print(f"原始数组: {array}")
array_zscore = np.array(list(map(lambda x: (x-np.mean(array))/np.std(array), array.flatten()))).round(decimals=2)
print(f"标准化后的数组: {array_zscore}")
print("标准化后均值: %.2f" % np.mean(array_zscore))
print("标准化后标准差: %.2f" % np.std(array_zscore))



原始数组: [[48 38 24 17 30 48 28 32 20 20]]
标准化后的数组: [ 1.65  0.71 -0.61 -1.27 -0.05  1.65 -0.24  0.14 -0.99 -0.99]
标准化后均值: 0.00
标准化后标准差: 1.00
